# Generated by Django 5.2 on 2025-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mostrar_precio',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar precio públicamente?'),
        ),
        migrations.AddField(
            model_name='page',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio'),
        ),
    ]
