# Generated by Django 5.2 on 2025-04-21 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuota mensual',
                'verbose_name_plural': 'cuotas mensuales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
