# Generated by Django 4.0.2 on 2025-02-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingday',
            options={'ordering': ['week_number', 'day_name']},
        ),
        migrations.AddField(
            model_name='trainingday',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
