# Generated by Django 4.0.2 on 2025-02-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile_age_profile_birth_date_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
